version: "5.0.2"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway1:
    build: ./gateway
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/payments
      - REDIS_HOST=redis
      - KAFKA_SERVER=kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka

  gateway2:
    build: ./gateway
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/payments
      - REDIS_HOST=redis
      - KAFKA_SERVER=kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka

  gateway3:
    build: ./gateway
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/payments
      - REDIS_HOST=redis
      - KAFKA_SERVER=kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - gateway1
      - gateway2
      - gateway3

  redis:
    image: redis
    ports:
      - "6379:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  bank_a:
    build: ./bank_a_adapter

  fraud_service:
    build: ./fraud_service

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  db-init:
    build: ./gateway
    command: python init_db.py
    depends_on:
      - postgres
